language: ruby

branches:
  only:
   - master

script:
 - "bundle exec jekyll build" 
 - ./build.sh

env:
  global:
   - secure: qhuhwykseRw3w0h73aQ92s2ZOpL065OWW7CUk8xZ2/BaBb+3+h3BVGijXt+F5N4J39lqcyL2fF8GXt+mS8rpJU8tfn3oPsrlFz0mvhuA1zV+nav2tr6QIUMHkqP2L+2jbkvJjHe29VNheEfrHjr7RO5g6G0/tv85HRXA64sdpf0=
