language: ruby
branches:
  only:
  - master
script:
- ./build.sh
env:
    secure: wWwPwSaNUhGVVcOB9+plfRA6VMfFc6zDRYBtNUQt+3Twccb3zE5C0QYoc4qRu228MVPlBtT4TP5GPN1rzcGzKqgOxe7oG8NbRVcqRCc+7XpYbhvY1J5wEf44BFEaQv/YrookLnHEtd+jvQ/plhq6PRvON5zy4tOM4H8LgMDaN54=
