language: ruby
branches:
  only:
  - master
script:
- ./build.sh
env:
  global:
  - secure: wg3poQxg4OBtyiYYA8Fa7pX9LmKvCFUjfEyHDznNKp5QJ3ufLUZ9+lCjlTlLZDTtzryVv2U2aLnW2dUQFiIs/UFNiOmr7Ax1pk15ttI3l3hURTP7lKlPcvnF9CmGB3Wpq0zdIfLMH0MUTq77nQFmJTR1hBV+OzlsY/FsYFMdpWU=
  - secure: qhuhwykseRw3w0h73aQ92s2ZOpL065OWW7CUk8xZ2/BaBb+3+h3BVGijXt+F5N4J39lqcyL2fF8GXt+mS8rpJU8tfn3oPsrlFz0mvhuA1zV+nav2tr6QIUMHkqP2L+2jbkvJjHe29VNheEfrHjr7RO5g6G0/tv85HRXA64sdpf0=
